## Silence Unmasked
## Waterstone Productions

########################################################################################
# Constants
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
SCREEN_X = -(SCREEN_WIDTH / 2)
SCREEN_Y = -(SCREEN_HEIGHT / 2)
SCREEN_Z = -10
SCREEN_MAXTIME = 180
SCREEN_MAXTIME_CUTSCENE = 450
SCREEN_DIM = 0.5544
SCREEN_NORMAL = 1.0
FONT_X = -300
FONT_Y = 200
FONT_Z = -2
RADIO_X = 0
RADIO_Y = 0
RADIO_Z = 5
OBJECT_X1 = 15
OBJECT_X2 = 138
OBJECT_X3 = 265
OBJECT_X4 = 392
OBJECT_X5 = 524
OBJECT_Y1 = 100
OBJECT_Y2 = 215
OBJECT_Y3 = 330
OBJECT_Y4 = 444
OBJECT_Z = -1
BUTTON_ARROW_SX = 476
BUTTON_ARROW_SY = 462
BUTTON_ARROW_WIDTH = 56
BUTTON_ARROW_HEIGHT = 54
BUTTON_INVENTORY_SX = 90
BUTTON_INVENTORY_SY = 460
BUTTON_INVENTORY_WIDTH = 310
BUTTON_INVENTORY_HEIGHT = 44 
BUTTON_SAVEGAME_SX = 562
BUTTON_SAVEGAME_SY = 434
BUTTON_SAVEGAME_WIDTH = 52
BUTTON_SAVEGAME_HEIGHT = 24
BUTTON_QUITGAME_SX = 562
BUTTON_QUITGAME_SY = 466
BUTTON_QUITGAME_WIDTH = 56
BUTTON_QUITGAME_HEIGHT = 22
EVENT_NOTHING = 0
EVENT_BUTTON_A = 1
EVENT_BUTTON_B = 2
EVENT_DEPTH = -1
CHASE_TIME_START = 700
CHASE_TIME_CLOAK = 300
CHASE_TIME_DIE = 0
CHASE_CHANCE_RANGE_START = 0
CHASE_CHANCE_RANGE_END = 200
CHASE_CHANCE_RANGE_DIVIDER = 10
LOADER_TYPE_NONE = ""
LOADER_TYPE_SPRITES = "sprite"
LOADER_TYPE_FONTS = "font"
LOADER_TYPE_RADIOS = "radio"
SAVE_FILENAME = "Savegame.dat"
HIDING_SPOT_REMINDERS = [
"I guess I could hide here if I needed to.",
"It looks like I could hide here.",
"Looks like there'd be plenty of space for a person to hide in."
]
########################################################################################
